chore(deps): bump github.com/pulumi/pulumi-kubernetes/sdk/v4 from 4.23.0 to 4.24.0 (#178)
Bumps [github.com/pulumi/pulumi-kubernetes/sdk/v4](https://github.com/pulumi/pulumi-kubernetes) from 4.23.0 to 4.24.0.
<details>
<summary>Release notes</summary>
<p><em>Sourced from <a href="https://github.com/pulumi/pulumi-kubernetes/releases">github.com/pulumi/pulumi-kubernetes/sdk/v4's releases</a>.</em></p>
<blockquote>
<h2>v4.24.0</h2>
<p>No release notes provided.</p>
</blockquote>
</details>
<details>
<summary>Changelog</summary>
<p><em>Sourced from <a href="https://github.com/pulumi/pulumi-kubernetes/blob/master/CHANGELOG.md">github.com/pulumi/pulumi-kubernetes/sdk/v4's changelog</a>.</em></p>
<blockquote>
<!-- raw HTML omitted -->
<h1>CHANGELOG</h1>
<h2>Unreleased</h2>
<h3>Added</h3>
<ul>
<li>Added a <code>plainHttp</code> option to the <code>v4.Chart</code> resource. (<a href="https://redirect.github.com/pulumi/pulumi-kubernetes/issues/3250">pulumi/pulumi-kubernetes#3250</a>)</li>
</ul>
<h3>Changed</h3>
<ul>
<li>
<p>The <code>pulumi.com/waitFor</code> annotation now uses an
<a href="https://www.rfc-editor.org/rfc/rfc9535.html">RFC9535</a>-compliant JSONPath
parser. This makes it possible to wait for more complex scenarios.</p>
<p>For example:</p>
<ul>
<li>
<p>To wait for a Pod's <code>status.phase</code> to be &quot;Running&quot; or &quot;Succeeded&quot;:</p>
<p><code>pulumi.com/waitFor: &quot;jsonpath={.status[?@ == 'Running' || @ == 'Succeeded' ]}&quot;</code></p>
</li>
<li>
<p>To wait for for an object to have a &quot;Failed&quot; <em>or</em> &quot;Complete&quot; condition with
a &quot;True&quot; value:</p>
<p><code>pulumi.com/waitFor: &quot;jsonpath={.conditions[?(@.type=='Failed'||@.type=='Complete')].status}=True</code></p>
</li>
</ul>
<p>(Tools like <a href="https://jsonpath.com">jsonpath.com</a> are very helpful for
ensuring your JSONPath expression works as expected.)</p>
<p>Importantly, please note that <code>kubectl wait --for=jsonpath=...</code> supports only
a <em>subset</em> of RFC9535. This means some complex <code>waitFor</code> annotations will not
be reproducible with <code>kubectl</code>.</p>
<p>Existing expressions should continue to work normally with one notable
exception: a selector like <code>.items[]</code> now requires an explicit wildcard, i.e.
<code>.items[*]</code>.</p>
<p>As a reminder, the <code>pulumi.com/waitFor</code> annotation is experimental and
subject to change. Similarly, RFC9535 is still only <em>proposed</em> and may also
change in the future.</p>
</li>
<li>
<p><code>enableConfigMapMutable</code> and <code>enableSecretMutable</code> are now stable.
(<a href="https://redirect.github.com/pulumi/pulumi-kubernetes/pull/3886">pulumi/pulumi-kubernetes#3886</a>)</p>
</li>
</ul>
<h3>Fixed</h3>
<ul>
<li>Helm resources all now use the correct <code>registry/config.json</code> file for
credentials. For backward-compatibility <code>registry.json</code> is preferred if
it exists. (<a href="https://redirect.github.com/pulumi/pulumi-kubernetes/issues/3606">pulumi/pulumi-kubernetes#3606</a>)</li>
</ul>
<!-- raw HTML omitted -->
</blockquote>
<p>... (truncated)</p>
</details>
<details>
<summary>Commits</summary>
<ul>
<li><a href="https://github.com/pulumi/pulumi-kubernetes/commit/d439b2074c81ec0a285492ea8c67cdd8a303306b"><code>d439b20</code></a> Update TestHelmRelease's metrics image and update test assertion (<a href="https://redirect.github.com/pulumi/pulumi-kubernetes/issues/3930">#3930</a>)</li>
<li><a href="https://github.com/pulumi/pulumi-kubernetes/commit/ffd70d544ccde81bb0765cbc820d0658a741c4d5"><code>ffd70d5</code></a> Mark SecretPatch inputs as secrets (<a href="https://redirect.github.com/pulumi/pulumi-kubernetes/issues/3893">#3893</a>)</li>
<li><a href="https://github.com/pulumi/pulumi-kubernetes/commit/65219f0e61a6b6859a06e1d14b184f168dbcc97b"><code>65219f0</code></a> Update dependency <code>@​pulumi/pulumi</code> to v3.206.0 (<a href="https://redirect.github.com/pulumi/pulumi-kubernetes/issues/3925">#3925</a>)</li>
<li><a href="https://github.com/pulumi/pulumi-kubernetes/commit/f1a455ad5f478c442314b7b5736a055fe66d5f6f"><code>f1a455a</code></a> Fix dotnet flakes (<a href="https://redirect.github.com/pulumi/pulumi-kubernetes/issues/3924">#3924</a>)</li>
<li><a href="https://github.com/pulumi/pulumi-kubernetes/commit/12a40978d90405c2618626dfde00608aa291b7e9"><code>12a4097</code></a> Update dependency <code>@​pulumi/gcp</code> to v9.4.0 (<a href="https://redirect.github.com/pulumi/pulumi-kubernetes/issues/3910">#3910</a>)</li>
<li><a href="https://github.com/pulumi/pulumi-kubernetes/commit/cafe4682584069c7b7f405714f45e33272cd8de3"><code>cafe468</code></a> Remove the 'BETA FEATURE' status in front of <code>enableConfigMapMutable</code> and `en...</li>
<li><a href="https://github.com/pulumi/pulumi-kubernetes/commit/967bd478ab9a8d73c0ae54a475718a7f2e921a07"><code>967bd47</code></a> Update a redis image (<a href="https://redirect.github.com/pulumi/pulumi-kubernetes/issues/3917">#3917</a>)</li>
<li><a href="https://github.com/pulumi/pulumi-kubernetes/commit/f52a5b29fd0977b28881782c6c86d1d9f2e3eb71"><code>f52a5b2</code></a> Automated upgrade: bump pulumi/pulumi to 3.205.0 (<a href="https://redirect.github.com/pulumi/pulumi-kubernetes/issues/3912">#3912</a>)</li>
<li><a href="https://github.com/pulumi/pulumi-kubernetes/commit/402da8a915a5787f3cb21a49bddb8e1e9680a825"><code>402da8a</code></a> Update dependency <code>@​pulumi/pulumi</code> to v3.205.0 (<a href="https://redirect.github.com/pulumi/pulumi-kubernetes/issues/3909">#3909</a>)</li>
<li><a href="https://github.com/pulumi/pulumi-kubernetes/commit/a2bb6d7a537d0431b9d98c216ef095069e124d0c"><code>a2bb6d7</code></a> Fix test cluster p-k version (<a href="https://redirect.github.com/pulumi/pulumi-kubernetes/issues/3902">#3902</a>)</li>
<li>Additional commits viewable in <a href="https://github.com/pulumi/pulumi-kubernetes/compare/v4.23.0...v4.24.0">compare view</a></li>
</ul>
</details>
<br />


[![Dependabot compatibility score](https://dependabot-badges.githubapp.com/badges/compatibility_score?dependency-name=github.com/pulumi/pulumi-kubernetes/sdk/v4&package-manager=go_modules&previous-version=4.23.0&new-version=4.24.0)](https://docs.github.com/en/github/managing-security-vulnerabilities/about-dependabot-security-updates#about-compatibility-scores)

Dependabot will resolve any conflicts with this PR as long as you don't alter it yourself. You can also trigger a rebase manually by commenting `@dependabot rebase`.

[//]: # (dependabot-automerge-start)
[//]: # (dependabot-automerge-end)

---

<details>
<summary>Dependabot commands and options</summary>
<br />

You can trigger Dependabot actions by commenting on this PR:
- `@dependabot rebase` will rebase this PR
- `@dependabot recreate` will recreate this PR, overwriting any edits that have been made to it
- `@dependabot merge` will merge this PR after your CI passes on it
- `@dependabot squash and merge` will squash and merge this PR after your CI passes on it
- `@dependabot cancel merge` will cancel a previously requested merge and block automerging
- `@dependabot reopen` will reopen this PR if it is closed
- `@dependabot close` will close this PR and stop Dependabot recreating it. You can achieve the same result by closing it manually
- `@dependabot show <dependency name> ignore conditions` will show all of the ignore conditions of the specified dependency
- `@dependabot ignore this major version` will close this PR and stop Dependabot creating any more for this major version (unless you reopen the PR or upgrade to it yourself)
- `@dependabot ignore this minor version` will close this PR and stop Dependabot creating any more for this minor version (unless you reopen the PR or upgrade to it yourself)
- `@dependabot ignore this dependency` will close this PR and stop Dependabot creating any more for this dependency (unless you reopen the PR or upgrade to it yourself)


</details>